# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- script: |
    sudo apt-get install docker -y
  displayName: Setting up docker cli

- script: |
    sudo docker run --name csound_emscripten_build_run -i sjamble/csound_emscripten
  displayName: Building the Csound emscripten build

- script: |
    sudo docker cp csound_emscripten_build_run:/csound/Emscripten/Csound6.13.0-Web.zip $(System.DefaultWorkingDirectory)/
  displayName: Extracting build file from docker image

- task: PublishPipelineArtifact@1
  inputs:
    path: $(System.DefaultWorkingDirectory)/Csound6.13.0-Web.zip
    artifact: Csound6.13.0-Web.zip
