name: Emscripten_build

on: 
  pull_request:
    branches:
    - develop
jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file DockerFiles/Emscripten/ --tag csound_emscripten_run
      
    - name: run the Docker image
      run: docker run --name cosund_test_run -i csound_emscripten_run
