name: Emscripten_build

on: 
  pull_request:
    branches:
    - develop
jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: run the Docker image
      run: docker run --name cosund_test_run -i sjamble/csound_emscripten
